objects/Employee__c.object
<CustomObject>
    <description>Store Employees from AT&amp;T: Custom object extension of User object to maintain attributes for specific tracks
. Retail Record Type: Identify Retail Employees type
. Center Record Type:  Identify Center-Care Employees type</description>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <description>Employee ATT UID</description>
        <externalId>true</externalId>
        <label>Employee Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Employee Last Name</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <label>Salesforce Profile Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARSM</fullName>
                </value>
                <value>
                    <fullName>DOS</fullName>
                </value>
                <value>
                    <fullName>RSC-MGR</fullName>
                </value>
                <value>
                    <fullName>RSC-REP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee relationship with Salesforce User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Record Type to group fields from Retail-Store type of Employee</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/EmployeeStoreRetail__c.object
<CustomObject>
    <description>For Retail Employees only: Stores Information about Employees and the different Stores assigned where they can operate. (Floating Reps and other floatings)</description>
    <fields>
        <fullName>Employee__c</fullName>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>RetailFloatingEmps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Employee Id + Store Id for Record Key Uniqueness</description>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to get the CenterPoint Profile assigned to an employee.</description>
        <formula>TEXT(Employee__r.SFProfileId__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Profile Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <description>Store assigned</description>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>EmployeeStoresRetail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to add/remove  entries from LeadShare object based on the EmployeeStoreRetail object association.</description>
        <formula>Employee__r.User__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User</label>
        <type>Text</type>
    </fields>
    <label>Employee Stores Retail</label>
    <nameField>
        <label>Employee Store Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Stores Retail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field defines the Store for which this Lead record was created</description>
        <label>Employee Location</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <description>This object will be used to save the details of various ATTR and AR stores for AT&amp;T</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeadTriggerHandlerTest.cls
/*
* This class will cover the test cases for various events and scenarios for Lead trigger
*/
@isTest
public with sharing class LeadTriggerHandlerTest {
    private static final String REP_PROFILE = 'Retail RSC Rep'; //Profile Name for the Retail Rep
    private static final String SM_PROFILE = 'Retail SM'; //Profile Name for the Store Manager
    private static final String ARSM_PROFILE = 'Retail ARSM'; //Profile Name for the ARSM
    private static final  map<String,String> profileIdToSfProfileMap = new map<String, String> (); //Stores the profile Id to SFProfile Name in the map

    private static Store__c store; //Store object to be linked to the Store

    /*
    * This method creates the setup data for the various scenarios of this test class
    */
    @TestSetup
    static void setupData(){
        List<User> userList = createUsers();
        store = createStore();
        List<Employee__c> empList = createEmployees(userList);
        List<EmployeeStoreRetail__c> empStoreList = createEmployeeStore(empList, store);
    }

    /*
    * This method creates the users required for the various scenarios for this tesr class
    */
    private static List<User> createUsers() {
        map<String,String> profileToSfProfileMap = new map<String, String> {
                                                                    REP_PROFILE  => RetailConstants.REP_POSITION,
                                                                    SM_PROFILE => RetailConstants.SM_POSITION,
                                                                    ARSM_PROFILE => RetailConstants.ARSM_POSITION
                                                    };
        list<String> profileNames = new list<String> {REP_PROFILE, SM_PROFILE, ARSM_PROFILE};
        list<Profile> profileList = [SELECT Id, Name FROM Profile WHERE Name IN :profileNames];
        List<User> userList = new list<User>();
        Integer i =0;
        for(Profile prf: profileList) {
            profileIdToSfProfileMap.put(prf.id, profileToSfProfileMap.get(prf.Name));
            User u = new User(
                LastName = 'test'+system.currentTimeMillis(),
                Email = 'test'+system.currentTimeMillis()+'@test.com',
                Username = 'test'+system.currentTimeMillis()+(i++)+'@test.com',
                CompanyName = 'TEST',
                Title = 'title',
                Alias = 'test',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                profileId = prf.id
            );
            userList.add(u);
        }
        insert userList;
        return userList;
    }

    /*
    * This method creates the employees for the various users passed in the parameter
    */
    private static List<Employee__c> createEmployees(List<User> userList) {
        List<Employee__c> employeeList = new List<Employee__c>();
        for(User u: userList) {
            Employee__c emp = new Employee__c(LastName__c = u.LastName,
                                                User__c = u.id,
                                                SFProfileId__c = profileIdToSfProfileMap.get(u.ProfileId),
                                                EmployeeId__c = ''+system.currentTimeMillis());
            employeeList.add(emp);
        }
        insert employeeList;
        return employeeList;
    }

    /*
    * This method creates the store record to be linked to the Lead
    */
    private static Store__c createStore() {
        Store__c store = new Store__c(Name = 'Test Store'+system.currentTimeMillis());
        insert store;
        return store;
    }

    /*
    * This method creates the Employee Store association records between Employee and Store 
    */
    private static List<EmployeeStoreRetail__c> createEmployeeStore(List<Employee__c> employeeList, Store__c store) {
        List<EmployeeStoreRetail__c> empStoreList = new List<EmployeeStoreRetail__c>();
        for(Employee__c emp: employeeList) {
            EmployeeStoreRetail__c empStore = new EmployeeStoreRetail__c(Employee__c = emp.id,
                                                Store__c = store.id,
                                                ExternalId__c = emp.id+'-'+store.id);
            empStoreList.add(empStore);
        }
        insert empStoreList;
        return empStoreList;
    }

    /*
    * This method tests the various cases for the Lead insertion
    */
    private static testMethod void testLeadInsert() {
        setupData();
        Test.startTest();
            Lead leadRec = new Lead(LastName = 'test'+system.currentTimeMillis(),
                                    Company = 'Test',
                                    Store__c = store.id
                                    );
            insert leadRec;
        Test.stopTest();

    }

    /*
    * This method tests the various cases for the Lead update
    */
    private static testMethod void testLeadUpdate() {
        setupData();
        Lead leadRec = new Lead(LastName = 'test'+system.currentTimeMillis(),
                                Company = 'Test',
                                Store__c = store.id
                            );
        insert leadRec;
        Store__c store2 = createStore();
        Test.startTest();
            leadRec.Store__c = store2.id;
            update leadRec;
        Test.stopTest();
    }
}