objects/Employee__c.object
<CustomObject>
    <description>Store Employees from AT&amp;T: Custom object extension of User object to maintain attributes for specific tracks
. Retail Record Type: Identify Retail Employees type
. Center Record Type:  Identify Center-Care Employees type</description>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <label>Salesforce Profile Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARSM</fullName>
                </value>
                <value>
                    <fullName>DOS</fullName>
                </value>
                <value>
                    <fullName>RSC-MGR</fullName>
                </value>
                <value>
                    <fullName>RSC-REP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/EmployeeStoreRetail__c.object
<CustomObject>
    <description>For Retail Employees only: Stores Information about Employees and the different Stores assigned where they can operate. (Floating Reps and other floatings)</description>
    <fields>
        <fullName>Employee__c</fullName>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>RetailFloatingEmps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to get the CenterPoint Profile assigned to an employee.</description>
        <formula>TEXT(Employee__r.SFProfileId__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Profile Id</label>
        <type>Text</type>
    </fields>
    <label>Employee Stores Retail</label>
    <nameField>
        <label>Employee Store Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Stores Retail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EmployeeTriggerHelper.cls
/*
* This class is called from the TriggerHelper to facilitate Employee Trigger to handle various scenarios to be covered for all events on Employee Object
* Currently, this class handles check employee promotion/demotion conditions and check if the profile is changed on the Employee
* Author: Rashmi Thippeswamy
*/
public class EmployeeTriggerHelper {
     /* 
    *This method is called on Employee object update to check the conditions for promotion/demotion
    */
    public static TriggerHelper.RoleMap checkEmployeeConditions(TriggerHelper.RoleMap roleMap,EmployeeStoreRetail__c empStoreRec ,Map<Id,Set<Id>> mapStoreVSuserId,Map<Id,Employee__c> mapEmpNew,Map<Id,Employee__c> mapEmpOld){
        //Case 1: Promotion from REP to SM
        if(String.isNotBlank(mapEmpNew.get(empStoreRec.Employee__c).SFProfileId__c) && String.isNotBlank(mapEmpOld.get(empStoreRec.Employee__c).SFProfileId__c)){
            if(mapEmpNew.get(empStoreRec.Employee__c).SFProfileId__c == RetailConstants.SM_POSITION && mapEmpOld.get(empStoreRec.Employee__c).SFProfileId__c  == RetailConstants.REP_POSITION){
                //create a map of( SM Role=>{STORE=>List<Promoted SM Users>})
                roleMap.mapRoleVSmapStoreUsrAdd = TriggerHelper.createRoleMap(roleMap.mapRoleVSmapStoreUsrAdd,mapStoreVSuserId,empStoreRec);
            }
            //Case 2: Promotion from SM to ARSM
            else if(mapEmpNew.get(empStoreRec.Employee__c).SFProfileId__c== RetailConstants.ARSM_POSITION && mapEmpOld.get(empStoreRec.Employee__c).SFProfileId__c  == RetailConstants.SM_POSITION){
                //create a map of( ARSM Role=>{STORE=>List<Promoted ARSM Users>})
                roleMap.mapRoleVSmapStoreUsrAdd = TriggerHelper.createRoleMap(roleMap.mapRoleVSmapStoreUsrAdd,mapStoreVSuserId,empStoreRec);
            }
            //Case 3: Demotion from SM to REP
            else if(mapEmpNew.get(empStoreRec.Employee__c).SFProfileId__c== RetailConstants.REP_POSITION && mapEmpOld.get(empStoreRec.Employee__c).SFProfileId__c  == RetailConstants.SM_POSITION){
                //create a map of( REP Role=>{STORE=>List<Demoted REP Users>})
                roleMap.mapRoleVSmapStoreUsrRem = TriggerHelper.createRoleMap(roleMap.mapRoleVSmapStoreUsrRem,mapStoreVSuserId,empStoreRec);
            }
            //Case 3: Demotion from  ARSM to SM
            else if(mapEmpNew.get(empStoreRec.Employee__c).SFProfileId__c== RetailConstants.SM_POSITION && mapEmpOld.get(empStoreRec.Employee__c).SFProfileId__c  == RetailConstants.ARSM_POSITION){
                //create a map of( SM Role=>{STORE=>List<Demoted SM Users>})
                roleMap.mapRoleVSmapStoreUsrRem = TriggerHelper.createRoleMap(roleMap.mapRoleVSmapStoreUsrRem,mapStoreVSuserId,empStoreRec);
            }
        } 
        return roleMap; 
    }
     /* 
    *This method is called on Employee object update to check if the SFProfileId__c field on Employee is changed to facilitate Promotion/Demotion
    */
    public static Map<Id,Employee__c> checkIfProfileIsChanged(Map<Id,Employee__c> mapEmpNew,Map<Id,Employee__c> mapEmpOld){
        Map<Id,Employee__c> mapEmployee = new Map<Id,Employee__c>();
        for(Id empId :mapEmpNew.keySet() ){
            if(String.isNotBlank(mapEmpNew.get(empId).SFProfileId__c) && String.isNotBlank(mapEmpOld.get(empId).SFProfileId__c) 
            && mapEmpNew.get(empId).SFProfileId__c != mapEmpOld.get(empId).SFProfileId__c){
                mapEmployee.put(empId,mapEmpNew.get(empId));
            }
        }
        return mapEmployee;
    }
}