objects/Employee__c.object
<CustomObject>
    <description>Store Employees from AT&amp;T: Custom object extension of User object to maintain attributes for specific tracks
. Retail Record Type: Identify Retail Employees type
. Center Record Type:  Identify Center-Care Employees type</description>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <label>Salesforce Profile Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARSM</fullName>
                </value>
                <value>
                    <fullName>DOS</fullName>
                </value>
                <value>
                    <fullName>RSC-MGR</fullName>
                </value>
                <value>
                    <fullName>RSC-REP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee relationship with Salesforce User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/EmployeeStoreRetail__c.object
<CustomObject>
    <description>For Retail Employees only: Stores Information about Employees and the different Stores assigned where they can operate. (Floating Reps and other floatings)</description>
    <fields>
        <fullName>Employee__c</fullName>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>RetailFloatingEmps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsExpired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field defines if the association is expired</description>
        <label>IsExpired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to get the CenterPoint Profile assigned to an employee.</description>
        <formula>TEXT(Employee__r.SFProfileId__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Profile Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <description>Store assigned</description>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>EmployeeStoresRetail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to add/remove  entries from LeadShare object based on the EmployeeStoreRetail object association.</description>
        <formula>Employee__r.User__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User</label>
        <type>Text</type>
    </fields>
    <label>Employee Stores Retail</label>
    <nameField>
        <label>Employee Store Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Stores Retail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field defines the Store for which this Lead record was created</description>
        <label>Employee Location</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <description>This object will be used to save the details of various ATTR and AR stores for AT&amp;T</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EmployeeStoreRetailTriggerTest.cls
@isTest
private  class EmployeeStoreRetailTriggerTest {
    private static TestDataFactory.TestWrapper dataFactoryWrap = new TestDataFactory.TestWrapper();
    private static TestDataFactory dataFactory = new TestDataFactory();
    @TestSetup
    static void makeData(){
        
        dataFactoryWrap = dataFactory.createTestData(3);
        System.debug('***** mapRoleVsUsers'+dataFactoryWrap.mapRoleVsUsers);
        System.debug('***** lstStore'+dataFactoryWrap.lstStore);
        System.debug('***** mapEmpRetailStoreVsRole'+dataFactoryWrap.mapEmpRetailStoreVsRole);
        System.debug('***** mapStoreVsMapRoleEmployee'+dataFactoryWrap.mapStoreVsMapRoleEmployee);
        System.debug('***** lstLead'+dataFactoryWrap.lstLead);
    }
    @IsTest
    static void testAddEmpStore(){
        //test lead share add on store addition to an emloyee
        Test.startTest();
        List<EmployeeStoreRetail__c> lstEmpStore = [SELECT id,SFProfileId__c,Store__c,User__c FROM EmployeeStoreRetail__c];
        for(LeadShare ls : [SELECT  id,LeadId,LeadAccessLevel,Lead.Store__c,UserOrGroupId FROM LeadShare WHERE LeadId IN(SELECT id FROM Lead)]){
            for(EmployeeStoreRetail__c esr :  lstEmpStore){
                if(esr.SFProfileId__c == RetailConstants.SM_POSITION && ls.Lead.Store__c == esr.Store__c && ls.UserOrGroupId == esr.User__c){
                        System.assertEquals(RetailConstants.LEAD_ACCESS_ALL, ls.LeadAccessLevel,'FAILED');
                }
                else if(esr.SFProfileId__c == RetailConstants.ARSM_POSITION && ls.Lead.Store__c == esr.Store__c && ls.UserOrGroupId == esr.User__c){
                        System.assertEquals(RetailConstants.LEAD_ACCESS_READ, ls.LeadAccessLevel,'FAILED');
                }
            }
        }
        Test.stopTest();
    }
    @IsTest
    static void testRemoveEmpStore(){
        //test lead share add on store addition to an emloyee
        
        List<EmployeeStoreRetail__c> lstEmpRetail = new List<EmployeeStoreRetail__c>();
        Set<Id> setStoreIds = new Set<Id>();
        List<LeadShare> lstLeadShare = new List<LeadShare>();
        List<User> lstUser =  [SELECT id FROM User WHERE Alias='talias'];
        for(EmployeeStoreRetail__c esr :  [SELECT id,isExpired__c,SFProfileId__c,Store__c,User__c FROM EmployeeStoreRetail__c WHERE Employee__r.User__c IN: lstUser ]){
            esr.isExpired__c = true;
            setStoreIds.add(esr.Store__c);
            lstEmpRetail.add(esr);
        }
        Test.startTest();
        update lstEmpRetail;
        System.debug('*** @@@@ lstEmpRetail'+lstEmpRetail);
        lstLeadShare = [SELECT id,LeadId,LeadAccessLevel,Lead.Store__c,UserOrGroupId FROM LeadShare WHERE Lead.Store__c IN:setStoreIds 
                        AND UserOrGroupId IN: lstUser AND RowCause !='Owner'];
        System.debug('*** '+lstLeadShare);
        SYSTEM.assert(lstLeadShare.isEmpty());
        Test.stopTest();
    }
    @IsTest
    static void testAddBackEmpStore(){
        //test lead share add on store addition to an emloyee
        
        List<EmployeeStoreRetail__c> lstEmpRetail = new List<EmployeeStoreRetail__c>();
        List<EmployeeStoreRetail__c> lstEmpRetailUpdate = new List<EmployeeStoreRetail__c>();
        Set<Id> setStoreIds = new Set<Id>();
        List<LeadShare> lstLeadShare = new List<LeadShare>();
        List<User> lstUser =  [SELECT id FROM User WHERE Alias='talias' ];
        for(EmployeeStoreRetail__c esr :  [SELECT id,isExpired__c,SFProfileId__c,Store__c,User__c FROM EmployeeStoreRetail__c 
                                           WHERE Employee__r.User__c IN: lstUser  ]){
            esr.isExpired__c = true;
            setStoreIds.add(esr.Store__c);
            lstEmpRetail.add(esr);
        }
        update lstEmpRetail;
        for(EmployeeStoreRetail__c esr : lstEmpRetail){
            esr.isExpired__c = false;
            lstEmpRetailUpdate.add(esr);
        }
        Test.startTest();
        update lstEmpRetailUpdate;
        System.debug('*** @@@@ lstEmpRetailUpdate'+lstEmpRetailUpdate);
        lstLeadShare = [SELECT id,LeadId,LeadAccessLevel,Lead.Store__c,UserOrGroupId FROM LeadShare WHERE Lead.Store__c IN:setStoreIds 
                        AND UserOrGroupId IN: lstUser AND RowCause !='Owner'];
        System.debug('*** @@@@ lstLeadShare'+lstLeadShare);
        System.debug('*** @@@@ lstLeadShare'+lstLeadShare.size());
        SYSTEM.assert(!lstLeadShare.isEmpty());
        Test.stopTest();
    }

}