objects/EmployeeStoreRetail__c.object
<CustomObject>
    <description>For Retail Employees only: Stores Information about Employees and the different Stores assigned where they can operate. (Floating Reps and other floatings)</description>
    <fields>
        <fullName>IsExpired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field defines if the association is expired</description>
        <label>IsExpired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <description>Store assigned</description>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>EmployeeStoresRetail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Employee Stores Retail</label>
    <nameField>
        <label>Employee Store Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Stores Retail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field defines the Store for which this Lead record was created</description>
        <label>Employee Location</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <description>This object will be used to save the details of various ATTR and AR stores for AT&amp;T</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EmployeeStoreRetailTriggerHelper.cls
/*
* This class is called from the Employee Store Retail  Trigger and subsequently from Trigger helper 
*to handle various scenarios to be covered for all events on EmployeeStore Retail  Object's insert / update
* Currently, this class handles checking conditions for add/remove store and redistribution of leads when a rep is removed from a store
* Author: Rashmi Thippeswamy
*/
public class EmployeeStoreRetailTriggerHelper {
     /* 
    *This method is called on Employee Store Retail object's insert/update to check the conditions for add/remove store 
    */
    public static TriggerHelper.RoleMap checkEmployeeStoreRetailConditions(TriggerHelper.RoleMap roleMap,EmployeeStoreRetail__c empStoreRec ,Map<Id,Set<Id>> mapStoreVSuserId,Map<Id,EmployeeStoreRetail__c> mapEmpStoreNew,Map<Id,EmployeeStoreRetail__c> mapEmpStoreOld){
        if(mapEmpStoreOld != NULL && !mapEmpStoreOld.isEmpty()){
            //if isExpired__c is checked then remove employee from store
            if(mapEmpStoreNew.get(empStoreRec.Id).IsExpired__c == true && mapEmpStoreOld.get(empStoreRec.Id).IsExpired__c == false){
                roleMap.mapRoleVSmapStoreUsrRem = TriggerHelper.createRoleMap(roleMap.mapRoleVSmapStoreUsrRem,mapStoreVSuserId,empStoreRec);
            }
             //if isExpired__c is unchecked then add employee to a store
            else if(mapEmpStoreNew.get(empStoreRec.Id).IsExpired__c == false && mapEmpStoreOld.get(empStoreRec.Id).IsExpired__c == true){
                roleMap.mapRoleVSmapStoreUsrAdd = TriggerHelper.createRoleMap(roleMap.mapRoleVSmapStoreUsrAdd,mapStoreVSuserId,empStoreRec);
            }
        }
        //if isExpired__c is unchecked during insert then add employee from store
        else{
            roleMap.mapRoleVSmapStoreUsrAdd = TriggerHelper.createRoleMap(roleMap.mapRoleVSmapStoreUsrAdd,mapStoreVSuserId,empStoreRec);
        }
      return roleMap;
    }
 /* 
    *This method is called on Employee Store Retail object's update to check if a rep who is removed from store
    *owns leads. Those leads gets redistributed within the store
*/
    public static List<Lead> redistributeLeads(List<LeadShare> lstleadShare){
        Map<Id,Set<Id>> mapStoreVSuserId = new Map<Id,Set<Id>>();
        Set<Id> setUserIds = new Set<Id>();
        Set<Id> setStoreIds = new Set<Id>();
        for(LeadShare ls : lstleadShare){
            //extract all the REPs who are owners of leads
            setUserIds.add(ls.UserOrGroupId);
            //extract all the stores belonging to those leads
            setStoreIds.add(ls.Lead.Store__c);
        }
        return RedistributeLeadHandler.redistributeLeads(setUserIds,setStoreIds, RetailConstants.EMP_REMOVE_LOCATION);
    }
}