objects/Employee__c.object
<CustomObject>
    <description>Store Employees from AT&amp;T: Custom object extension of User object to maintain attributes for specific tracks
. Retail Record Type: Identify Retail Employees type
. Center Record Type:  Identify Center-Care Employees type</description>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <label>Salesforce Profile Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARSM</fullName>
                </value>
                <value>
                    <fullName>DOS</fullName>
                </value>
                <value>
                    <fullName>RSC-MGR</fullName>
                </value>
                <value>
                    <fullName>RSC-REP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee relationship with Salesforce User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/EmployeeStoreRetail__c.object
<CustomObject>
    <description>For Retail Employees only: Stores Information about Employees and the different Stores assigned where they can operate. (Floating Reps and other floatings)</description>
    <fields>
        <fullName>Employee__c</fullName>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>RetailFloatingEmps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to get the CenterPoint Profile assigned to an employee.</description>
        <formula>TEXT(Employee__r.SFProfileId__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Profile Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <description>Store assigned</description>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>EmployeeStoresRetail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to add/remove  entries from LeadShare object based on the EmployeeStoreRetail object association.</description>
        <formula>Employee__r.User__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User</label>
        <type>Text</type>
    </fields>
    <label>Employee Stores Retail</label>
    <nameField>
        <label>Employee Store Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Stores Retail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field defines the Store for which this Lead record was created</description>
        <label>Employee Location</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <description>This object will be used to save the details of various ATTR and AR stores for AT&amp;T</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeadSharingHandler.cls
/*
* This class contains all the business logic for sharing a Lead with various personas
*/
public with sharing class LeadSharingHandler {
    /*
    * This method is called from the Lead after insert and update and manages programmtic sharing od the record
    * Params
    * leadsMap -> Trigger.newMap()
    * oldMap -> Trigger.oldMap() -> null for insert
    */
    public static void processLeadSharing(Map<Id,Lead> leadsMap, map<Id, Lead> oldMap) {
        set<Id> storeIdSet = new set<Id>();
        map<Id,list<Id>> storeToLeadMap = new map<Id,list<Id>>();
        map<Id,list<Id>> oldstoreToLeadMap = new map<Id,list<Id>>();
        set<Id> oldUserIdSet = new set<Id>();
        list<LeadShare> leadShareList = new list<LeadShare>();
        for(Lead leadRec: leadsMap.values()) {
            Lead oldLead = null;
            //In Case of update check if the store has been changed and then only process the sharing
            if(oldMap != null) {
                oldLead = oldMap.get(leadRec.Id);
                /*Whenever the owner of the record is changed, the records shared via Manual Sharing are deleted
                * For standard objects, we cannot defined a rowcause. 
                * Hence, on owner change, the records shared via programmatic sharing are also lost. 
                * This scenario will reshared the records on Owner change
                */
                if(oldLead != null && oldLead.ownerId != leadRec.ownerId) {
                    storeIdSet.add(leadRec.store__c);
                    storeToLeadMap = populateStoreToLeadMap(storeToLeadMap, leadRec);
                }
                if(oldLead != null && oldLead.store__c != leadRec.store__c) {
                    storeIdSet.add(leadRec.store__c);
                    storeIdSet.add(oldLead.store__c);
                    storeToLeadMap = populateStoreToLeadMap(storeToLeadMap, leadRec);
                    oldstoreToLeadMap = populateStoreToLeadMap(oldstoreToLeadMap, oldLead);
                }
            } 
            //For insert, process the sharing, only if the store for the Lead is populated
            else if(leadRec.store__c != null) {
                storeIdSet.add(leadRec.store__c);
                storeToLeadMap = populateStoreToLeadMap(storeToLeadMap, leadRec);
            }
        }
        //Fetch relevant users for sharing from the Employee Store Association 
        List<EmployeeStoreRetail__c> employeeStoreList = [Select Employee__c, Employee__r.User__c, Store__c, Employee__r.SFProfileId__c FROM EmployeeStoreRetail__c WHERE Store__c IN :storeIdSet AND Employee__r.SFProfileId__c IN :RetailConstants.SHARE_POSITIONS];

        for(EmployeeStoreRetail__c empStoreRec: employeeStoreList) {
            //This will be used to process deletion of existing LeadShare records when the store is changed
            if(oldstoreToLeadMap.containsKey(empStoreRec.Store__c)) {
                oldUserIdSet.add(empStoreRec.Employee__r.User__c);
            }
            if(storeToLeadMap.containsKey(empStoreRec.Store__c)) {
                for(Id leadId :  storeToLeadMap.get(empStoreRec.Store__c)) {
                    String accessLevel = RetailConstants.LEAD_ACCESS_READ;
                    if(empStoreRec.Employee__r.SFProfileId__c.equalsIgnoreCase(RetailConstants.SM_POSITION))
                        accessLevel = RetailConstants.LEAD_ACCESS_ALL;
                    leadShareList.add(createLeadShare(accessLevel, leadId, empStoreRec.Employee__r.User__c));
                }
            }
        }

        //If the Store for the Lead has been changed, delete the existing LeadShare records 
        list<LeadShare> deleteLeadShareList = [Select id FROM LeadShare WHERE LeadId IN :leadsMap.keySet() AND UserOrGroupId IN :oldUserIdSet];
        if(deleteLeadShareList.size() > 0) {
            Database.DeleteResult[] deleteSaveResult = Database.delete(deleteLeadShareList, false);
        }
        Database.SaveResult[] insertSaveResult = Database.insert(leadShareList, false);
    }

    /*
    * This method populates the Store Id to List of Lead Id map
    */
    private static map<Id, list<id>> populateStoreToLeadMap(map<Id, list<id>> storeToLeadMap, Lead leadRec) {
        list<Id> leadIdList = new list<Id>();
        if(storeToLeadMap.containsKey(leadRec.store__c)) {
            leadIdList = storeToLeadMap.get(leadRec.store__c);
        }
        leadIdList.add(leadRec.Id);
        storeToLeadMap.put(leadRec.store__c, leadIdList);
        return storeToLeadMap;
    }

    /*
    * This method creats the LeadShare record based on the parameters
    * accessLevel -> Access Level for the record, Read/Edit
    * leadId -> Id of the Lead for record shring
    * userId  -> Id of the user or group for record sharing
    */
    private static LeadShare createLeadShare(String accessLevel, Id leadId, Id userId) {
        LeadShare leadShareRec = new LeadShare(
                                                LeadAccessLevel = accessLevel, 
                                                LeadId = leadId,
                                                RowCause = Schema.LeadShare.RowCause.Manual,
                                                UserOrGroupId = userId);
        return leadShareRec;
    }
}