objects/Employee__c.object
<CustomObject>
    <description>Store Employees from AT&amp;T: Custom object extension of User object to maintain attributes for specific tracks
. Retail Record Type: Identify Retail Employees type
. Center Record Type:  Identify Center-Care Employees type</description>
    <fields>
        <fullName>HomeStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Retail Field. Unique Home Store Location associate to the employee. Used mostly for Lead Distribution process.</description>
        <label>Home Store Location</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee relationship with Salesforce User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field defines the Store for which this Lead record was created</description>
        <label>Employee Location</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <description>This object will be used to save the details of various ATTR and AR stores for AT&amp;T</description>
    <fields>
        <fullName>OpusId__c</fullName>
        <description>This field defines the unique identifier by Store used by Opus</description>
        <label>Opus Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeadForm.cls
/*
 * This class will have all the methods for the Lead Capture (New Lead) custom form
 * Author: Reshma Jewrani
 * Created Date: 5/12/2020 
 */
public without sharing class LeadForm {
    
    @AuraEnabled(cacheable=true)
    public static Store__c getHomeStore() {
        //Get platform Cache if available else get home store
        String storeId = StoreController.getStoreFromCache();
        system.debug('From Cache-->'+StoreId);
        if(storeId != null && storeId != '') {
            List<Store__c> storeList = [SELECT id, Name 
                                                        FROM Store__c
                                                        WHERE Id = :storeId];
            if(storeList.size() > 0) {
                return storeList.get(0);
            }
        } else {
            
            Store__c homeStore = new Store__c();
            List<Employee__c> homeStoreList = [SELECT id, HomeStoreLocation__c, HomeStoreLocation__r.Name 
                                                            FROM Employee__c 
                                                            WHERE User__c = :UserInfo.getUserId()];
            if(homeStoreList.size() > 0 && homeStoreList.get(0).HomeStoreLocation__c != null) {
                homeStore.Id = homeStoreList.get(0).HomeStoreLocation__c;
                homeStore.Name = homeStoreList.get(0).HomeStoreLocation__r.Name;
                return homeStore;
            }
        }
        return null;
    }
    @AuraEnabled
    public static Lead updateLead(Lead leadRecord) {
        system.debug(leadRecord);
        leadRecord.IsUnreadByOwner = false;
        update leadRecord;
        return leadRecord;
    }
    @AuraEnabled(cacheable=true)
    public static Store__c getStoreFromOpusId(String storeId) {
        system.debug('storeId--?'+storeId);
        List<Store__c> storeList = [SELECT OpusId__c, id, Name 
                                                        FROM Store__c
                                                        WHERE OpusId__c = :storeId];
        system.debug('storeList--?'+storeList);
        if(storeList.size() > 0) {
            return storeList.get(0);
        } else {
            return getHomeStore();
        }
    }
}