objects/Employee__c.object
<CustomObject>
    <description>Store Employees from AT&amp;T: Custom object extension of User object to maintain attributes for specific tracks
. Retail Record Type: Identify Retail Employees type
. Center Record Type:  Identify Center-Care Employees type</description>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <label>Salesforce Profile Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARSM</fullName>
                </value>
                <value>
                    <fullName>DOS</fullName>
                </value>
                <value>
                    <fullName>RSC-MGR</fullName>
                </value>
                <value>
                    <fullName>RSC-REP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee relationship with Salesforce User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/EmployeeStoreRetail__c.object
<CustomObject>
    <description>For Retail Employees only: Stores Information about Employees and the different Stores assigned where they can operate. (Floating Reps and other floatings)</description>
    <fields>
        <fullName>Employee__c</fullName>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>RetailFloatingEmps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsExpired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field defines if the association is expired</description>
        <label>IsExpired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SFProfileId__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to get the CenterPoint Profile assigned to an employee.</description>
        <formula>TEXT(Employee__r.SFProfileId__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Profile Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <description>Store assigned</description>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Employee Stores Retail</relationshipLabel>
        <relationshipName>EmployeeStoresRetail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Retail Field. Used to easy the custom SOQL to add/remove  entries from LeadShare object based on the EmployeeStoreRetail object association.</description>
        <formula>Employee__r.User__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User</label>
        <type>Text</type>
    </fields>
    <label>Employee Stores Retail</label>
    <nameField>
        <label>Employee Store Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Stores Retail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <description>This object will be used to save the details of various ATTR and AR stores for AT&amp;T</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EmployeeStoreRetailHelper.cls
public class EmployeeStoreRetailHelper {
    public class RoleMap{
        public Map<String,Map<Id,Set<Id>>> mapRoleVSmapStoreUsrAdd;
        public Map<String,Map<Id,Set<Id>>> mapRoleVSmapStoreUsrRem;
        public RoleMap(){
            mapRoleVSmapStoreUsrAdd = new Map<String,Map<Id,Set<Id>>>();
            mapRoleVSmapStoreUsrRem = new Map<String,Map<Id,Set<Id>>>(); 
        }
        
    }
	public static LeadShare createLeadShareInstance(String accessLevel, Id leadId, Id userId) {
        LeadShare leadShareRec = new LeadShare(
                                                LeadAccessLevel = accessLevel, 
                                                LeadId = leadId,
                                                RowCause = Schema.LeadShare.RowCause.Manual,
                                                UserOrGroupId = userId);
        return leadShareRec;
    }
    
    public static EmployeeStoreRetailHelper.RoleMap getEmployeeRoleMapping(List<SObject> lstEmpStoreNewSObj,
                                                                    List<SObject> lstEmpStoreOldSObj,
                                                                    Map<Id,SObject> mapEmpStoreNewSObj,
                                                                    Map<Id,SObject> mapEmpStoreOldSObj){ 
        List<EmployeeStoreRetail__c> lstEmpStoreNew = new List<EmployeeStoreRetail__c>();
        List<EmployeeStoreRetail__c> lstEmpStoreOld =new List<EmployeeStoreRetail__c>();
        Map<Id,EmployeeStoreRetail__c> mapEmpStoreNew = new Map<Id,EmployeeStoreRetail__c>();
        Map<Id,EmployeeStoreRetail__c> mapEmpStoreOld = new Map<Id,EmployeeStoreRetail__c>();                                                                     
        EmployeeStoreRetailHelper.RoleMap roleMap = new EmployeeStoreRetailHelper.RoleMap();
        Map<String,Map<Id,Set<Id>>> mapRoleVSmapStoreUsrAdd = new Map<String,Map<Id,Set<Id>>>();
        Map<String,Map<Id,Set<Id>>> mapRoleVSmapStoreUsrRem = new Map<String,Map<Id,Set<Id>>>(); 
        Map<Id,Set<Id>> mapStoreVSuserId = new Map<Id,Set<Id>>();                                                                
        lstEmpStoreNew =(List<EmployeeStoreRetail__c>)lstEmpStoreNewSObj;
        lstEmpStoreOld =(List<EmployeeStoreRetail__c>)lstEmpStoreOldSObj;
        mapEmpStoreNew = (Map<Id,EmployeeStoreRetail__c>)mapEmpStoreNewSObj;
        mapEmpStoreOld = (Map<Id,EmployeeStoreRetail__c>)mapEmpStoreOldSObj;
        for(EmployeeStoreRetail__c empStoreRec : [Select Employee__c, IsExpired__c,Employee__r.User__c, Store__c, Employee__r.SFProfileId__c FROM EmployeeStoreRetail__c WHERE Id IN :lstEmpStoreNew]){
            if(mapEmpStoreOld != NULL && !mapEmpStoreOld.isEmpty()){
                if(mapEmpStoreNew.get(empStoreRec.Id).IsExpired__c == true && mapEmpStoreOld.get(empStoreRec.Id).IsExpired__c == false){
                    mapRoleVSmapStoreUsrRem = createRoleMap(mapRoleVSmapStoreUsrRem,mapStoreVSuserId,empStoreRec);
                }
                else if(mapEmpStoreNew.get(empStoreRec.Id).IsExpired__c == false && mapEmpStoreOld.get(empStoreRec.Id).IsExpired__c == true){
                    mapRoleVSmapStoreUsrAdd = createRoleMap(mapRoleVSmapStoreUsrAdd,mapStoreVSuserId,empStoreRec);
                }
            }
            else{
            	mapRoleVSmapStoreUsrAdd = createRoleMap(mapRoleVSmapStoreUsrAdd,mapStoreVSuserId,empStoreRec);
            }
        }
        roleMap.mapRoleVSmapStoreUsrAdd = mapRoleVSmapStoreUsrAdd;
        roleMap.mapRoleVSmapStoreUsrRem = mapRoleVSmapStoreUsrRem;                                                              
        return roleMap;
    }
    
    public static Map<String,Map<Id,Set<Id>>> createRoleMap(Map<String,Map<Id,Set<Id>>> mapRoleVSmapStoreUsr,Map<Id,Set<Id>> mapStoreVSuserId,EmployeeStoreRetail__c empStoreRec){
        
        if(mapRoleVSmapStoreUsr.containsKey(empStoreRec.Employee__r.SFProfileId__c)){
            mapStoreVSuserId = mapRoleVSmapStoreUsr.get(empStoreRec.Employee__r.SFProfileId__c);
            if(mapStoreVSuserId.containsKey(empStoreRec.Store__c)){
                mapStoreVSuserId.get(empStoreRec.Store__c).add(empStoreRec.Employee__r.User__c);
            }
            else{
                mapStoreVSuserId.put(empStoreRec.Store__c,new Set<Id>{empStoreRec.Employee__r.User__c});
            }
        }
        else{
            mapStoreVSuserId = new Map<Id,Set<Id>>();
            mapStoreVSuserId.put(empStoreRec.Store__c,new Set<Id>{empStoreRec.Employee__r.User__c});
            mapRoleVSmapStoreUsr.put(empStoreRec.Employee__r.SFProfileId__c,mapStoreVSuserId);
        }
        return mapRoleVSmapStoreUsr;
    }
    public static List<LeadShare> insertLeadShare(List<LeadShare> lstLeadShare){
        if(!lstLeadShare.isEmpty()){
            insert lstLeadShare;
        }
        return lstLeadShare;
    }
    
    public static List<LeadShare> deleteLeadShare(List<LeadShare> lstLeadShare){
        if(!lstLeadShare.isEmpty()){
            delete lstLeadShare;
        }
        return lstLeadShare;
    }
      
}